### ISSUE TITLE
How to train in Occlusion LineMOD dataset ?

### ISSUE THREAD

**Issue by ZJU-PLP** [Gorilla-Lab-SCUT/DCL-Net#1]
Hi, authors:

I cannot find the bash script file of **training on Occlusion LineMOD dataset** when to reproduce your paper's experiments. Could you mind sharing the details or code about training on Occlusion LineMOD dataset?

**Comment by LHY-HongyangLi** [comment]
Following HybridPose, we trained our model only on LineMod dataset, and evaluate on both LineMod/Occlusion LineMod datasets.

**Comment by ZJU-PLP** [comment]
> Following HybridPose, we trained our model only on LineMod dataset, and evaluate on both LineMod/Occlusion LineMod datasets.

Ok, I see. Thanks for your reply. I'll have a try.
