### ISSUE TITLE
Finding errors when running bash scripts/script_train_LM.sh

### ISSUE THREAD

**Issue by ZJU-PLP** [Gorilla-Lab-SCUT/DCL-Net#3]
@LHY-HongyangLi 
Hi, I meet the error when to run bash scripts/script_train_LM.sh.
![image](https://user-images.githubusercontent.com/32757213/192989505-254b6d7f-d283-44b2-99ed-a807146db85d.png)

**Comment by LHY-HongyangLi** [comment]
I'm sorry for my mistake, I have fixed the bugs you will meet when you are training DCL-Net. I am busy with my work so the quality of this reposity is not so well.

**Comment by ZJU-PLP** [comment]
Ok, thanks for your reply.
