### ISSUE TITLE
How long to train in YCB dataset(including GPU device)?

### ISSUE THREAD

**Issue by ZJU-PLP** [Gorilla-Lab-SCUT/DCL-Net#4]
Hi, Hongyang:

Could you mind sharing the details of training process?  I find that the training process is very slow and about 1.5h one epoch in my GTX 1080Ti by script  `bash scripts/script_train_YCBV_stage1.sh`. However, your provided pretrained model is 84 epoch. It cloud be very long to train.

**Comment by LHY-HongyangLi** [comment]
Indeed, Training DCL-Net on YCBV is really source consuming, I did experiments on GTX2080Ti, and spent about 4-5 days to train stage1 and about 2 days to train stage2.

**Comment by ZJU-PLP** [comment]
> Indeed, Training DCL-Net on YCBV is really source consuming, I did experiments on GTX2080Ti, and spent about 4-5 days to train stage1 and about 2 days to train stage2.

Ok, I see.  Thanks for your reply.
